# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('date', models.CharField(default='01 Jan', help_text='Date (no year) DD MMM ', max_length=6)),
                ('year', models.CharField(default='0000', help_text='Year YYYY', max_length=5)),
                ('announcement_title', models.CharField(default='Announcement here!', help_text='Title of your announcement post', max_length=100)),
                ('announcement_text', models.TextField(default='', help_text='Type your new announcement here', max_length=500)),
                ('author', models.CharField(default='', help_text='Type your name as you want it to appear', max_length=100)),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.CreateModel(
            name='FeaturedCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('image', mezzanine.core.fields.FileField(blank=True, help_text="A square, transparent image (or white background) to represent the company on the frontpage slider.  Make sure it's a square.", max_length=255, null=True, verbose_name='Image')),
                ('link_to', models.CharField(default='http://', help_text="A link to the company's application site", max_length=1000)),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('heading', models.CharField(help_text='Put atitle here or something', max_length=200)),
                ('hptime', models.CharField(default='00:00:00', help_text='Time, Data, Location', max_length=200)),
                ('hpdate', models.CharField(default='00/00/00', help_text='Date', max_length=200)),
                ('hploc', models.CharField(default='Aaa, Aaa', help_text='Location', max_length=200)),
                ('subheading', models.CharField(default='Write something here already', help_text='Some text explaining what the career fair is', max_length=1000)),
                ('IconText1', models.CharField(default='IconText1', max_length=200)),
                ('IconTitle1', models.CharField(default='IconTitle1', max_length=50)),
                ('IconText2', models.CharField(default='IconText2', max_length=200)),
                ('IconTitle2', models.CharField(default='IconTitle2', max_length=50)),
                ('IconText3', models.CharField(default='IconText3', max_length=200)),
                ('IconTitle3', models.CharField(default='IconTitle3', max_length=50)),
                ('IconText4', models.CharField(default='IconText4', max_length=200)),
                ('IconTitle4', models.CharField(default='IconTitle4', max_length=50)),
                ('featured_companies_heading', models.CharField(default='Featured Companies', max_length=200)),
                ('announcement_header', models.CharField(default='Announcements', help_text='Title for announcements field', max_length=30)),
                ('content_heading', models.CharField(default='About us!', max_length=200)),
                ('latest_posts_heading', models.CharField(default='Latest Posts', max_length=200)),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Home page',
                'verbose_name_plural': 'Home pages',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='HomePage_slider',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('heading', models.CharField(help_text='The heading under the icon blurbs', max_length=200)),
                ('subheading', models.CharField(help_text='The subheading just below the heading', max_length=200)),
                ('featured_works_heading', models.CharField(default='Featured Works', max_length=200)),
                ('content_heading', models.CharField(default='About us!', max_length=200)),
                ('latest_posts_heading', models.CharField(default='Latest Posts', max_length=200)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='IconBlurb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('icon', mezzanine.core.fields.FileField(max_length=255, verbose_name='Image')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Optional, if provided clicking the blurb will go here.', max_length=2000)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blurbs', to='theme.HomePage')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='theme.HomePage')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.AddField(
            model_name='featuredcompany',
            name='homepage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_companies', to='theme.HomePage'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='homepage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='theme.HomePage'),
        ),
    ]
