# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='heading',
            field=models.CharField(help_text='Put title here or something', max_length=200),
        ),
    ]
