# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('theme', '0002_auto_20160523_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('super_heading', models.CharField(max_length=100)),
                ('heading1', models.CharField(help_text='Header for column 1', max_length=50)),
                ('heading2', models.CharField(help_text='Header for column 1', max_length=50)),
                ('heading3', models.CharField(help_text='Header for column 1', max_length=50)),
                ('LeftColumn', models.CharField(help_text='Blurb under heading1', max_length=3000)),
                ('MidColumn', models.CharField(help_text='Blurb under heading1', max_length=3000)),
                ('RightColumn', models.CharField(help_text='Blurb under heading1', max_length=50)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('name', models.CharField(help_text='Enter the name of the staff memeber here', max_length=100)),
                ('position', models.CharField(help_text='Enter their position among the career fair staff', max_length=100)),
                ('bio', models.CharField(help_text='Enter a short bio of that person and their duties', max_length=1000)),
                ('image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('aboutpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='theme.AboutPage')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.RemoveField(
            model_name='homepage_slider',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='HomePage_slider',
        ),
    ]
