# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20160523_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='BottomRow',
            field=models.TextField(default='', help_text='Blurb under heading4', max_length=3000),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='heading4',
            field=models.CharField(default='Our Team', help_text='Header for bottom blurb', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='LeftColumn',
            field=models.TextField(default='', help_text='Blurb under heading1', max_length=3000),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='MidColumn',
            field=models.TextField(default='', help_text='Blurb under heading2', max_length=3000),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='RightColumn',
            field=models.TextField(default='', help_text='Blurb under heading3', max_length=3000),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='heading2',
            field=models.CharField(help_text='Header for column 2', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='heading3',
            field=models.CharField(help_text='Header for column 3', max_length=50),
        ),
    ]
