# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0009_companyprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='resume',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='mood',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
