# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0012_auto_20160525_1151'),
    ]

    operations = [
    ]
