# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0016_remove_companyprofile_company_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='has_submitted_payment',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='is_company',
        ),
    ]
