# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0018_auto_20160525_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_uid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
