# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0019_companyprofile_company_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='id',
        ),
    ]
