# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0024_auto_20160525_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='uploads/company_images'),
        ),
    ]
