# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0026_registrationpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationpage',
            options={'ordering': ('_order',), 'verbose_name': 'Registration Page', 'verbose_name_plural': 'Registration Pages'},
        ),
    ]
