# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0027_auto_20160525_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='company',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='days_attending',
            new_name='DaysAttending',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='grade_level_wanted',
            new_name='GradeLevelWanted',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='has_submitted_payment',
            new_name='HasSubmittedPayment',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='is_company',
            new_name='IsCompany',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='majors_wanted',
            new_name='MajorsWanted',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='picture',
            new_name='Picture',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='user',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='website',
            new_name='Website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='relocation',
            field=models.BooleanField(default=False),
        ),
    ]
