# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0029_auto_20160525_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='DaysAttending',
            new_name='days_attending',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='GradeLevelWanted',
            new_name='grade_level_wanted',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='HasSubmittedPayment',
            new_name='has_submitted_payment',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='IsCompany',
            new_name='is_company',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='MajorsWanted',
            new_name='majors_wanted',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='Picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='Website',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='relocation',
            new_name='open_to_relocation',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hometown',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
