# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0030_auto_20160525_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='how_are_you_feeling_today',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
