# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0032_auto_20160526_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
