# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0033_userprofile_full_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='StudentProfile',
        ),
    ]
