# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0034_auto_20160526_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='IconUrl1',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AddField(
            model_name='homepage',
            name='IconUrl2',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AddField(
            model_name='homepage',
            name='IconUrl3',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AddField(
            model_name='homepage',
            name='IconUrl4',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
