# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0035_auto_20160526_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='IconText1',
            field=models.CharField(blank=True, default='IconText1', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='IconText2',
            field=models.CharField(blank=True, default='IconText2', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='IconText3',
            field=models.CharField(blank=True, default='IconText3', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='IconText4',
            field=models.CharField(blank=True, default='IconText4', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='IconTitle1',
            field=models.CharField(blank=True, default='IconTitle1', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='IconTitle2',
            field=models.CharField(blank=True, default='IconTitle2', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='IconTitle3',
            field=models.CharField(blank=True, default='IconTitle3', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='IconTitle4',
            field=models.CharField(blank=True, default='IconTitle4', max_length=50),
        ),
    ]
