# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0038_auto_20160526_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='picture',
        ),
    ]
