# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0041_auto_20160526_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='website',
            new_name='application_website',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='picture',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='phone',
            new_name='public_phone_number',
        ),
    ]
