# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0042_auto_20160527_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationpage',
            name='email_from',
        ),
        migrations.AddField(
            model_name='registrationpage',
            name='text_under_map',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='registrationpage',
            name='google_maps_api_key',
            field=models.CharField(blank=True, help_text='Google how to obtain a google maps key for the location mueller center and paste it here', max_length=200),
        ),
    ]
