# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0043_auto_20160527_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpage',
            name='email_from',
            field=models.EmailField(blank=True, help_text='The address the email will be sent from', max_length=254, verbose_name='From address'),
        ),
        migrations.AlterField(
            model_name='registrationpage',
            name='google_maps_api_key',
            field=models.CharField(blank=True, help_text='Google how to obtain a google maps key for the location mueller center and past it here', max_length=200),
        ),
    ]
