# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0045_auto_20160527_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmoryTableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
