# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('theme', '0046_armorytabledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableReservationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
        migrations.AddField(
            model_name='armorytabledata',
            name='dimension_x',
            field=models.IntegerField(blank=True, default=16),
        ),
        migrations.AddField(
            model_name='armorytabledata',
            name='dimension_y',
            field=models.IntegerField(blank=True, default=18),
        ),
    ]
