# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0048_auto_20160528_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorytabledata',
            name='reservations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tables',
            field=models.TextField(null=True),
        ),
    ]
