# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0049_auto_20160528_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='tables',
            field=models.TextField(default='[]'),
        ),
    ]
