# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0052_studentprofile_gpa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'get_latest_by': 'creation_date'},
        ),
    ]
