# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0054_auto_20160528_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='created_at',
            new_name='creation_date',
        ),
    ]
