# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0056_studentsearchformmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsearchformmodel',
            old_name='GPA',
            new_name='minimum_GPA',
        ),
    ]
