# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0057_auto_20160529_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
