# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0058_auto_20160529_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
