# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0060_auto_20160529_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='public_phone_number',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='open_to_relocation',
            field=models.BooleanField(default=False, help_text='Open to relocation?'),
        ),
    ]
