# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0061_auto_20160529_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('volunteer_choice', multiselectfield.db.fields.MultiSelectField(choices=[('Armory', 'Armory'), ('Food', 'Food'), ('Something else', 'Something else')], max_length=26)),
                ('days_available', multiselectfield.db.fields.MultiSelectField(choices=[('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15)),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
            },
        ),
    ]
