# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 18:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theme', '0062_volunteer'),
    ]

    operations = [
    ]
