# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0064_remove_volunteer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
