# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('theme', '0065_delete_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorUsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('super_heading', models.CharField(max_length=100)),
                ('heading1', models.CharField(help_text='Your heading for the page', max_length=50)),
                ('text', models.TextField(default='', help_text='The big blob of text under the heading', max_length=3000)),
                ('contact', models.CharField(help_text='Who they should contact', max_length=100)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
    ]
