# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0066_sponsoruspage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsearchformmodel',
            old_name='full_name',
            new_name='name',
        ),
    ]
