# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0067_auto_20160530_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='full_name',
            new_name='first_name',
        ),
    ]
