# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0069_studentprofile_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_name',
        ),
    ]
