# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0070_auto_20160530_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
