# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0072_companyrep'),
    ]

    operations = [
    ]
