# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 00:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theme', '0074_remove_companyrep_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrep',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
