# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0076_auto_20160530_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='misc_info_body',
            field=models.CharField(default='About us', help_text='Body for misc info field', max_length=2000),
        ),
        migrations.AddField(
            model_name='homepage',
            name='misc_info_header',
            field=models.CharField(default='About us', help_text='Title for misc info field', max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='misc_info_redirect',
            field=models.CharField(default='About us', help_text='url for hyperlink at end of the misc info field', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='misc_info_redirect_text',
            field=models.CharField(default='About us', help_text='Actual text of the hyperlink', max_length=200),
        ),
    ]
