# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('theme', '0077_auto_20160604_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('heading', models.CharField(help_text='Put title here or something', max_length=200)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('Question', mezzanine.core.fields.RichTextField(verbose_name='Question')),
                ('Answer', mezzanine.core.fields.RichTextField(verbose_name='Answer')),
                ('faqpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='theme.FAQPage')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.RemoveField(
            model_name='tablereservationpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='TableReservationPage',
        ),
    ]
