# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0078_auto_20160604_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Question',
            new_name='question',
        ),
    ]
