# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 01:27
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0079_auto_20160604_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='BottomRow',
            field=mezzanine.core.fields.RichTextField(default='', help_text='Blurb under heading4', max_length=3000),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='LeftColumn',
            field=mezzanine.core.fields.RichTextField(default='', help_text='Blurb under heading1', max_length=3000),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='MidColumn',
            field=mezzanine.core.fields.RichTextField(default='', help_text='Blurb under heading2', max_length=3000),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='RightColumn',
            field=mezzanine.core.fields.RichTextField(default='', help_text='Blurb under heading3', max_length=3000),
        ),
    ]
