# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 01:31
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0080_auto_20160604_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='subheading',
            field=mezzanine.core.fields.RichTextField(default='Write something here already', help_text='Some text explaining what the career fair is', max_length=1000),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='bio',
            field=mezzanine.core.fields.RichTextField(help_text='Enter a short bio of that person and their duties', max_length=1000),
        ),
    ]
