# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0082_auto_20160604_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='total_bill',
            field=models.IntegerField(default=500, null=True),
        ),
    ]
