# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('theme', '0084_auto_20160605_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='page_ptr',
        ),
        migrations.AlterModelOptions(
            name='paypalinfo',
            options={'verbose_name': 'PayPal Info', 'verbose_name_plural': 'PayPal Info'},
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
