# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0085_auto_20160605_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalinfo',
            name='item_name',
            field=models.CharField(default='SHPE Company Career Fair Registration Fee 2016', help_text='What is the name of the item/service they are buying?', max_length=400),
        ),
    ]
