# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0086_paypalinfo_item_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paypalinfo',
            options={},
        ),
        migrations.RemoveField(
            model_name='paypalinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paypalinfo',
            name='friday_price',
        ),
        migrations.RemoveField(
            model_name='paypalinfo',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='paypalinfo',
            name='price_per_alumni_rep',
        ),
        migrations.RemoveField(
            model_name='paypalinfo',
            name='price_per_rep',
        ),
        migrations.RemoveField(
            model_name='paypalinfo',
            name='saturday_price',
        ),
    ]
