# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0087_auto_20160605_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paypalinfo',
            options={'verbose_name': 'PayPal Info', 'verbose_name_plural': 'PayPal Info'},
        ),
        migrations.AddField(
            model_name='paypalinfo',
            name='email',
            field=models.EmailField(default='', help_text='The email account associated with whatever paypal account you plan on using', max_length=254),
        ),
        migrations.AddField(
            model_name='paypalinfo',
            name='friday_price',
            field=models.IntegerField(default=500, help_text="Friday's price"),
        ),
        migrations.AddField(
            model_name='paypalinfo',
            name='item_name',
            field=models.CharField(default='SHPE Company Career Fair Registration Fee 2016', help_text='What is the name of the item/service they are buying?', max_length=400),
        ),
        migrations.AddField(
            model_name='paypalinfo',
            name='price_per_alumni_rep',
            field=models.IntegerField(default=0, help_text='Price per RPI alumni representative'),
        ),
        migrations.AddField(
            model_name='paypalinfo',
            name='price_per_rep',
            field=models.IntegerField(default=75, help_text='Price per representative'),
        ),
        migrations.AddField(
            model_name='paypalinfo',
            name='saturday_price',
            field=models.IntegerField(default=500, help_text="Saturday's price"),
        ),
    ]
