# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0089_auto_20160605_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalinfo',
            name='price_per_table',
            field=models.IntegerField(default=100, help_text='Price per table'),
        ),
        migrations.AddField(
            model_name='paypalinfo',
            name='sponsorship',
            field=models.IntegerField(default=0, help_text='How much do you want to charge for sponsorships?'),
        ),
    ]
