# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('theme', '0092_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('heading', models.CharField(help_text='Put title here or something', max_length=200)),
                ('pricing_info', mezzanine.core.fields.RichTextField(help_text='Enter a nicely formatted pricing page here, complete with any sponsorship information you could think of.', max_length=30000)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
    ]
