# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0093_pricingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='This is the ranking of this package. Each Sponsorship package should be ranked from worst to best.  1 is worst, highest is best.')),
                ('title', models.CharField(help_text='What do you name this package? This will appear on the sponsorus page', max_length=100)),
                ('description', mezzanine.core.fields.RichTextField(help_text='In detail, describe the amenities of the package.  Be sure to format it nicely because whatever you write here will be displayed on the sponsor us page.')),
                ('price', models.IntegerField(help_text='Finally, put the price.')),
            ],
        ),
        migrations.RemoveField(
            model_name='sponsoruspage',
            name='heading1',
        ),
        migrations.RemoveField(
            model_name='sponsoruspage',
            name='text',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='interview_rooms',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='interview_times',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsorshippackage',
            name='sponsoruspage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_package', to='theme.SponsorUsPage'),
        ),
    ]
