# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 05:15
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0094_auto_20160607_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoruspage',
            name='contact',
            field=mezzanine.core.fields.RichTextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
