# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0095_sponsoruspage_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='interview_times',
            new_name='interview_friday_from',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='interview_rooms',
            new_name='interview_rooms_friday',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='interview_friday_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='interview_rooms_saturdays',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='interview_satuday_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='interview_saturday_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
