# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0096_auto_20160608_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='interview_rooms_saturdays',
            new_name='interview_rooms_saturday',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='interview_satuday_to',
            new_name='interview_saturday_to',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='sponsor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
