# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 02:48
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0098_auto_20160608_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoruspage',
            name='blurb',
            field=mezzanine.core.fields.RichTextField(default='', help_text='Some paragraph of text above the segment of the page where the sponsorship packages are listed', max_length=3000),
            preserve_default=False,
        ),
    ]
