# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0100_auto_20160609_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='tables',
            new_name='friday_tables',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='saturday_tables',
            field=models.TextField(default='[]'),
        ),
    ]
