# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0101_auto_20160609_0207'),
    ]

    operations = [
    ]
