# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0102_auto_20160612_2100'),
    ]

    operations = [
    ]
