# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0103_auto_20160612_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
    ]
