# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 02:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theme', '0104_auto_20160612_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('public_email', models.EmailField(blank=True, max_length=120)),
                ('company', models.CharField(max_length=30)),
                ('company_website', models.CharField(blank=True, max_length=1000)),
                ('logo', models.ImageField(blank=True, upload_to='uploads/company_images')),
                ('days_attending', multiselectfield.db.fields.MultiSelectField(choices=[('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15)),
                ('majors_wanted', multiselectfield.db.fields.MultiSelectField(choices=[('Aeronautical Engineering', 'Aeronautical Engineering'), ('Applied Physics', 'Applied Physics'), ('Architecture', 'Architecture'), ('Biochemistry and Biophysics', 'Biochemistry and Biophysics'), ('Bioinformatics and Molecular Biology', 'Bioinformatics and Molecular Biology'), ('Biology', 'Biology'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Building Science', 'Building Science'), ('Business and Management', 'Business and Management'), ('Chemical Engineering', 'Chemical Engineering'), ('Chemistry', 'Chemistry'), ('Civil Engineering', 'Civil Engineering'), ('Cognitive Science', 'Cognitive Science'), ('Communication', 'Communication'), ('Computer and Systems Engineering', 'Computer and Systems Engineering'), ('Computer Science', 'Computer Science'), ('Design, Innovation, and Society', 'Design, Innovation, and Society'), ('Economics', 'Economics'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronic Arts', 'Electronic Arts'), ('Electronic Media, Arts, and Communication', 'Electronic Media, Arts, and Communication'), ('Environmental Engineering', 'Environmental Engineering'), ('Environmental Science', 'Environmental Science'), ('Games and Simulation Arts and Sciences', 'Games and Simulation Arts and Sciences'), ('Geology', 'Geology'), ('Hydrogeology', 'Hydrogeology'), ('Industrial and Management Engineering', 'Industrial and Management Engineering'), ('Information Technology and Web Science', 'Information Technology and Web Science'), ('Interdisciplinary Science', 'Interdisciplinary Science'), ('Materials Engineering', 'Materials Engineering'), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Nuclear Engineering', 'Nuclear Engineering'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Psychology', 'Psychology'), ('Science, Technology, and Society', 'Science, Technology, and Society'), ('Sustainability Studies', 'Sustainability Studies')], max_length=818)),
                ('grade_level_wanted', multiselectfield.db.fields.MultiSelectField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate'), ('PhD', 'PhD')], max_length=45)),
                ('mood', models.TextField(blank=True, max_length=1000)),
                ('company_bio', models.TextField(blank=True, max_length=1000)),
                ('has_submitted_payment', models.BooleanField(default=False)),
                ('how_are_you_feeling_today', models.CharField(blank=True, max_length=1000)),
                ('friday_tables', models.TextField(default='[]')),
                ('saturday_tables', models.TextField(default='[]')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('reps', models.TextField(default='')),
                ('reps_alumni', models.TextField(default='', null=True)),
                ('number_of_representatives', models.IntegerField(default=1)),
                ('number_of_tables', models.IntegerField(default=0)),
                ('sponsor', models.CharField(blank=True, default='', max_length=100)),
                ('total_bill', models.IntegerField(default=500, null=True)),
                ('interview_rooms_friday', models.IntegerField(default=0, null=True)),
                ('interview_friday_from', models.CharField(blank=True, max_length=15, null=True)),
                ('interview_friday_to', models.CharField(blank=True, max_length=15, null=True)),
                ('interview_rooms_saturday', models.IntegerField(default=0, null=True)),
                ('interview_saturday_from', models.CharField(blank=True, max_length=15, null=True)),
                ('interview_saturday_to', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
