# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0105_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='tables',
            field=models.TextField(default='[]', null=True),
        ),
    ]
