# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('theme', '0106_companyprofile_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('heading', models.CharField(help_text='Title here or something', max_length=200)),
                ('left_column_header', models.CharField(help_text='left column', max_length=100)),
                ('mid_column_header', models.CharField(help_text='mid column', max_length=100)),
                ('right_column_header', models.CharField(help_text='right column', max_length=100)),
                ('left_column_blurb', mezzanine.core.fields.RichTextField(help_text='field under left column', max_length=3000)),
                ('mid_column_blurb', mezzanine.core.fields.RichTextField(help_text='field under left column', max_length=3000)),
                ('right_column_blurb', mezzanine.core.fields.RichTextField(help_text='field under left column', max_length=3000)),
                ('field', mezzanine.core.fields.RichTextField(help_text='gigantic field under everything', max_length=10000)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
        migrations.RemoveField(
            model_name='paypalinfo',
            name='sponsorship',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_non_profit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyrep',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.CompanyProfile'),
        ),
        migrations.AddField(
            model_name='paypalinfo',
            name='weekend_price',
            field=models.IntegerField(default=1050, help_text='Discounted price for companies attending both days'),
        ),
        migrations.AlterField(
            model_name='paypalinfo',
            name='friday_price',
            field=models.IntegerField(default=550, help_text="Friday's base fee.  THis includes the registration fee, one table, two reps, breakfast and lunch"),
        ),
        migrations.AlterField(
            model_name='paypalinfo',
            name='price_per_rep',
            field=models.IntegerField(default=75, help_text='Price per representative beyond the first two'),
        ),
        migrations.AlterField(
            model_name='paypalinfo',
            name='price_per_table',
            field=models.IntegerField(default=100, help_text='Price per table beyond the first'),
        ),
        migrations.AlterField(
            model_name='paypalinfo',
            name='saturday_price',
            field=models.IntegerField(default=560, help_text="Saturday's base fee.  Also includes registration fee, one table, two reps, etc"),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='GPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
