# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0109_auto_20160614_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrep',
            name='company',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
