# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0110_auto_20160614_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tippage',
            old_name='field',
            new_name='bottom_field',
        ),
        migrations.AddField(
            model_name='tippage',
            name='bottom_header',
            field=models.CharField(default='title', help_text='title for gigantic field', max_length=100),
            preserve_default=False,
        ),
    ]
