# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0111_auto_20160614_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='friday_number_of_tables',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='saturday_number_of_tables',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyrep',
            name='days_attending',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Friday', 'Friday'), ('Saturday', 'Saturday')], default=['friday'], max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorshippackage',
            name='num_free_reps',
            field=models.IntegerField(default=0, help_text='Number of free reps the company recieve for this package'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorshippackage',
            name='num_free_tables',
            field=models.IntegerField(default=0, help_text='Number of free tables the company would recieve for picking this sponsorship'),
            preserve_default=False,
        ),
    ]
