# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0112_auto_20160614_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshippackage',
            name='discount',
            field=models.IntegerField(default=0, help_text='Some amount to be subtracted from their end total? (free registration or something)'),
        ),
    ]
