# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0113_sponsorshippackage_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this item', max_length=200)),
                ('price', models.IntegerField(help_text='The price of this item')),
            ],
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='sponsorshipitem',
            field=models.ManyToManyField(related_name='sponsorshipitem', to='theme.SponsorshipItem'),
        ),
    ]
