# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0117_auto_20160615_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='reps_alumni',
            field=models.ManyToManyField(null=True, related_name='alumni', to='theme.CompanyRep'),
        ),
    ]
