# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0118_auto_20160615_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='reps_alumni',
            field=models.ManyToManyField(blank=True, related_name='alumni', to='theme.CompanyRep'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='tables',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
