# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0119_auto_20160615_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='sponsorshipitem',
            field=models.ManyToManyField(blank=True, related_name='sponsorshipitem', to='theme.SponsorshipItem'),
        ),
    ]
