# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0120_auto_20160615_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsoruspage',
            old_name='super_heading',
            new_name='misc_items',
        ),
        migrations.RenameField(
            model_name='sponsoruspage',
            old_name='blurb',
            new_name='misc_items_blurb',
        ),
        migrations.AddField(
            model_name='sponsoruspage',
            name='page_blurb',
            field=mezzanine.core.fields.RichTextField(default='blurb', help_text='Some paragraph explaining the beautiful of sponsorhsips', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsoruspage',
            name='page_header',
            field=models.CharField(default='Sponoorship', max_length=100),
        ),
    ]
