# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0121_auto_20160616_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='mood',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='friday_representatives',
            field=models.ManyToManyField(blank=True, null=True, related_name='fri_reps', to='theme.CompanyRep'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='saturday_representatives',
            field=models.ManyToManyField(blank=True, null=True, related_name='sat_reps', to='theme.CompanyRep'),
        ),
    ]
