# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0125_auto_20160629_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='how_are_you_feeling_today',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='public_email',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company',
            field=models.CharField(max_length=60, verbose_name='Company'),
        ),
    ]
