# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0126_auto_20160709_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company',
            field=models.CharField(max_length=60, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_bio',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Company bio'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_website',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Company website'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='days_attending',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15, verbose_name='Days attending'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='friday_number_of_tables',
            field=models.IntegerField(default=0, verbose_name='Friday # of tables'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='friday_representatives',
            field=models.ManyToManyField(blank=True, related_name='_companyprofile_friday_representatives_+', to='theme.CompanyRep'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='friday_tables',
            field=models.TextField(default='[]', verbose_name='Friday table locations'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='grade_level_wanted',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate'), ('PhD', 'PhD')], max_length=45, verbose_name='Grade level wanted'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='has_submitted_payment',
            field=models.BooleanField(default=False, verbose_name='Has submitted payment'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='is_non_profit',
            field=models.BooleanField(default=False, verbose_name='Is non-profit'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, upload_to='uploads/company_images', verbose_name='Company logo'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='majors_wanted',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Aeronautical Engineering', 'Aeronautical Engineering'), ('Applied Physics', 'Applied Physics'), ('Architecture', 'Architecture'), ('Biochemistry and Biophysics', 'Biochemistry and Biophysics'), ('Bioinformatics and Molecular Biology', 'Bioinformatics and Molecular Biology'), ('Biology', 'Biology'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Building Science', 'Building Science'), ('Business and Management', 'Business and Management'), ('Chemical Engineering', 'Chemical Engineering'), ('Chemistry', 'Chemistry'), ('Civil Engineering', 'Civil Engineering'), ('Cognitive Science', 'Cognitive Science'), ('Communication', 'Communication'), ('Computer and Systems Engineering', 'Computer and Systems Engineering'), ('Computer Science', 'Computer Science'), ('Design, Innovation, and Society', 'Design, Innovation, and Society'), ('Economics', 'Economics'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronic Arts', 'Electronic Arts'), ('Electronic Media, Arts, and Communication', 'Electronic Media, Arts, and Communication'), ('Environmental Engineering', 'Environmental Engineering'), ('Environmental Science', 'Environmental Science'), ('Games and Simulation Arts and Sciences', 'Games and Simulation Arts and Sciences'), ('Geology', 'Geology'), ('Hydrogeology', 'Hydrogeology'), ('Industrial and Management Engineering', 'Industrial and Management Engineering'), ('Information Technology and Web Science', 'Information Technology and Web Science'), ('Interdisciplinary Science', 'Interdisciplinary Science'), ('Materials Engineering', 'Materials Engineering'), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Nuclear Engineering', 'Nuclear Engineering'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Psychology', 'Psychology'), ('Science, Technology, and Society', 'Science, Technology, and Society'), ('Sustainability Studies', 'Sustainability Studies')], max_length=818, verbose_name='Majors wanted'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='number_of_representatives',
            field=models.IntegerField(default=1, verbose_name='Number of representatives'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='number_of_tables',
            field=models.IntegerField(default=0, verbose_name='Number of tables'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='reps',
            field=models.ManyToManyField(related_name='_companyprofile_reps_+', to='theme.CompanyRep'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='reps_alumni',
            field=models.ManyToManyField(blank=True, related_name='_companyprofile_reps_alumni_+', to='theme.CompanyRep'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='saturday_number_of_tables',
            field=models.IntegerField(default=0, verbose_name='Saturday # of tables'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='saturday_representatives',
            field=models.ManyToManyField(blank=True, related_name='_companyprofile_saturday_representatives_+', to='theme.CompanyRep'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='saturday_tables',
            field=models.TextField(default='[]', verbose_name='Saturday table locations'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='sponsor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sponsorship choice'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='sponsorshipitem',
            field=models.ManyToManyField(blank=True, related_name='_companyprofile_sponsorshipitem_+', to='theme.SponsorshipItem'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='tables',
            field=models.TextField(blank=True, default='[]', null=True, verbose_name='Staff assigned tables'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='total_bill',
            field=models.IntegerField(default=500, null=True, verbose_name='Total bill'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last updated'),
        ),
    ]
