# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0127_auto_20160709_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpage',
            name='show_sponsorship_items',
            field=models.BooleanField(default=True),
        ),
    ]
