# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0128_registrationpage_show_sponsorship_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpage',
            name='email_template_html',
            field=models.FileField(blank=True, help_text='Should be identical to the text template except with added html', upload_to='uploads/company_iamges', verbose_name='Same as above except with HTML'),
        ),
        migrations.AddField(
            model_name='registrationpage',
            name='email_template_text',
            field=models.FileField(blank=True, help_text='Look at the one provided for an example', upload_to='uploads/company_images', verbose_name='Text template of invoice in the case that the html template does not render'),
        ),
    ]
