# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0131_auto_20160724_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqpage',
            options={'ordering': ('_order',), 'verbose_name': 'FAQ page', 'verbose_name_plural': 'FAQ Pages'},
        ),
    ]
