# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0132_auto_20160802_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('committee_name', models.CharField(default='Committee name', help_text='Name of committee', max_length=100)),
                ('aboutpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='theme.AboutPage')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='aboutpage',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='theme.Committee'),
        ),
    ]
