# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('theme', '0134_auto_20160802_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('heading', models.CharField(help_text='Put title here', max_length=500)),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Faq page',
                'verbose_name_plural': 'Faq Pages',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='question',
            name='faqpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='theme.FAQsPage'),
        ),
        migrations.DeleteModel(
            name='FAQPage',
        ),
    ]
