# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0135_auto_20160802_0246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQsPage',
            new_name='FAQPage',
        ),
    ]
