# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 19:49
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0137_auto_20160802_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tippage',
            name='bottom_field',
        ),
        migrations.RemoveField(
            model_name='tippage',
            name='bottom_header',
        ),
        migrations.RemoveField(
            model_name='tippage',
            name='left_column_blurb',
        ),
        migrations.RemoveField(
            model_name='tippage',
            name='left_column_header',
        ),
        migrations.RemoveField(
            model_name='tippage',
            name='mid_column_blurb',
        ),
        migrations.RemoveField(
            model_name='tippage',
            name='mid_column_header',
        ),
        migrations.RemoveField(
            model_name='tippage',
            name='right_column_blurb',
        ),
        migrations.RemoveField(
            model_name='tippage',
            name='right_column_header',
        ),
        migrations.AddField(
            model_name='tippage',
            name='body',
            field=mezzanine.core.fields.RichTextField(default='aaa', help_text='Insert tips here', verbose_name='Body'),
        ),
    ]
