# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0138_auto_20160921_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tippage',
            name='heading',
        ),
    ]
