# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0139_remove_tippage_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrep',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
