# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 18:38
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0140_companyrep_is_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='minor',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('------------', '-----------'), ('Acoustics', 'Acoustics'), ('Air and Space Leadership Studies', 'Air and Space Leadership Studies'), ('Architecture', 'Architecture'), ('Astrobiology', 'Astrobiology'), ('Astronomy', 'Astronomy'), ('Astrophysics', 'Astrophysics'), ('Biochemistry', 'Biochemistry'), ('Biology', 'Biology'), ('Biophysics', 'Biophysics'), ('Brain and Brain Behavior', 'Brain and Brain Behavior'), ('Chemistry', 'Chemistry'), ('Civil Engineering', 'Civil Engineering'), ('Chinese', 'Chinese'), ('Cognition', 'Cognition'), ('Communication', 'Communication'), ('Community and Health Psychology', 'Community and Health Psychology'), ('Computer Science', 'Computer Science'), ('Computer and Systems Engineering', 'Computer and Systems Engineering'), ('Electrical Power Engineering', 'Electrical Power Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronic Arts', 'Electronic Arts'), ('Electronic Media, Arts, and Communication', 'Electronic Media, Arts, and Communication'), ('Energy', 'Energy'), ('Entrepreneurship', 'Entrepreneurship'), ('Environmental Engineering', 'Environmental Engineering'), ('Environmental Science', 'Environmental Science'), ('Finance', 'Finance'), ('Games and Simulation Arts and Sciences', 'Games and Simulation Arts and Sciences'), ('Geology', 'Geology'), ('Game Studies', 'Game Studies'), ('Gender, Science and Technology', 'Gender, Science and Technology'), ('History of Architecture', 'History of Architecture'), ('Hydrogeology', 'Hydrogeology'), ('Human-Computer Interaction', 'Human-Computer Interaction'), ('Human Factors in Psychology', 'Human Factors in Psychology'), ('Industrial/Organizational Psychology', 'Industrial/Organizational Psychology'), ('Industrial and Management Engineering', 'Industrial and Management Engineering'), ('Lighting', 'Lighting'), ('Literature', 'Literature'), ('Logic, Computation and Mind', 'Logic, Computation and Mind'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('Materials Engineering', 'Materials Engineering'), ('Mathematics', 'Mathematics'), ('Military Studies', 'Military Studies'), ('Music', 'Music'), ('Origins of Life', 'Origins of Life'), ('Philosophy of Human Values and Society', 'Philosophy of Human Values and Society'), ('Philosophy of Logic, Computation and Mind', 'Philosophy of Logic, Computation and Mind'), ('Philosophy of Science and Technology', 'Philosophy of Science and Technology'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Professional Writing', 'Professional Writing'), ('Psychology', 'Psychology'), ('Science, Technology, and Society', 'Science, Technology, and Society'), ('Social Psychology', 'Social Psychology'), ('Sports Psychology', 'Sports Psychology'), ('Sustainability Studies', 'Sustainability Studies'), ('Studio Arts', 'Studio Arts'), ('Technology Commercialization and Entrepreneurship', 'Technology Commercialization and Entrepreneurship')], max_length=1216),
        ),
    ]
